package modelo;
// Generated 30/08/2018 16:01:07 by Hibernate Tools 4.3.1



/**
 * Pedidos generated by hbm2java
 */
public class Pedidos  implements java.io.Serializable {


     private Integer id;
     private int idUsuario;
     private String calleOrigen;
     private String nroOrigen;
     private String pisoOrigen;
     private String deptoOrigen;
     private String calleDestino;
     private String nroDestino;
     private String pisoDestino;
     private String deptoDestino;
     private String detalle;
     private double totalEstimado;
     private double totalComision;
     private String formaPago;
     private double pagaCon;
     private double vuelto;
     private int idavuelta;
     private String ciudad;

    public Pedidos() {
    }

	
    public Pedidos(int idUsuario, String calleOrigen, String nroOrigen, String calleDestino, String nroDestino, String detalle, double totalEstimado, double totalComision, String formaPago, double pagaCon, double vuelto, int idavuelta, String ciudad) {
        this.idUsuario = idUsuario;
        this.calleOrigen = calleOrigen;
        this.nroOrigen = nroOrigen;
        this.calleDestino = calleDestino;
        this.nroDestino = nroDestino;
        this.detalle = detalle;
        this.totalEstimado = totalEstimado;
        this.totalComision = totalComision;
        this.formaPago = formaPago;
        this.pagaCon = pagaCon;
        this.vuelto = vuelto;
        this.idavuelta = idavuelta;
        this.ciudad = ciudad;
    }
    public Pedidos(int idUsuario, String calleOrigen, String nroOrigen, String pisoOrigen, String deptoOrigen, String calleDestino, String nroDestino, String pisoDestino, String deptoDestino, String detalle, double totalEstimado, double totalComision, String formaPago, double pagaCon, double vuelto, int idavuelta, String ciudad) {
       this.idUsuario = idUsuario;
       this.calleOrigen = calleOrigen;
       this.nroOrigen = nroOrigen;
       this.pisoOrigen = pisoOrigen;
       this.deptoOrigen = deptoOrigen;
       this.calleDestino = calleDestino;
       this.nroDestino = nroDestino;
       this.pisoDestino = pisoDestino;
       this.deptoDestino = deptoDestino;
       this.detalle = detalle;
       this.totalEstimado = totalEstimado;
       this.totalComision = totalComision;
       this.formaPago = formaPago;
       this.pagaCon = pagaCon;
       this.vuelto = vuelto;
       this.idavuelta = idavuelta;
       this.ciudad = ciudad;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getCalleOrigen() {
        return this.calleOrigen;
    }
    
    public void setCalleOrigen(String calleOrigen) {
        this.calleOrigen = calleOrigen;
    }
    public String getNroOrigen() {
        return this.nroOrigen;
    }
    
    public void setNroOrigen(String nroOrigen) {
        this.nroOrigen = nroOrigen;
    }
    public String getPisoOrigen() {
        return this.pisoOrigen;
    }
    
    public void setPisoOrigen(String pisoOrigen) {
        this.pisoOrigen = pisoOrigen;
    }
    public String getDeptoOrigen() {
        return this.deptoOrigen;
    }
    
    public void setDeptoOrigen(String deptoOrigen) {
        this.deptoOrigen = deptoOrigen;
    }
    public String getCalleDestino() {
        return this.calleDestino;
    }
    
    public void setCalleDestino(String calleDestino) {
        this.calleDestino = calleDestino;
    }
    public String getNroDestino() {
        return this.nroDestino;
    }
    
    public void setNroDestino(String nroDestino) {
        this.nroDestino = nroDestino;
    }
    public String getPisoDestino() {
        return this.pisoDestino;
    }
    
    public void setPisoDestino(String pisoDestino) {
        this.pisoDestino = pisoDestino;
    }
    public String getDeptoDestino() {
        return this.deptoDestino;
    }
    
    public void setDeptoDestino(String deptoDestino) {
        this.deptoDestino = deptoDestino;
    }
    public String getDetalle() {
        return this.detalle;
    }
    
    public void setDetalle(String detalle) {
        this.detalle = detalle;
    }
    public double getTotalEstimado() {
        return this.totalEstimado;
    }
    
    public void setTotalEstimado(double totalEstimado) {
        this.totalEstimado = totalEstimado;
    }
    public double getTotalComision() {
        return this.totalComision;
    }
    
    public void setTotalComision(double totalComision) {
        this.totalComision = totalComision;
    }
    public String getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(String formaPago) {
        this.formaPago = formaPago;
    }
    public double getPagaCon() {
        return this.pagaCon;
    }
    
    public void setPagaCon(double pagaCon) {
        this.pagaCon = pagaCon;
    }
    public double getVuelto() {
        return this.vuelto;
    }
    
    public void setVuelto(double vuelto) {
        this.vuelto = vuelto;
    }
    public int isIdavuelta() {
        return this.idavuelta;
    }
    
    public void setIdavuelta(int idavuelta) {
        this.idavuelta = idavuelta;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    @Override
    public String toString() {
        return "Pedidos{" + "id=" + id + ", idUsuario=" + idUsuario + ", calleOrigen=" + calleOrigen + ", nroOrigen=" + nroOrigen + ", pisoOrigen=" + pisoOrigen + ", deptoOrigen=" + deptoOrigen + ", calleDestino=" + calleDestino + ", nroDestino=" + nroDestino + ", pisoDestino=" + pisoDestino + ", deptoDestino=" + deptoDestino + ", detalle=" + detalle + ", totalEstimado=" + totalEstimado + ", totalComision=" + totalComision + ", formaPago=" + formaPago + ", pagaCon=" + pagaCon + ", vuelto=" + vuelto + ", idavuelta=" + idavuelta + ", ciudad=" + ciudad + '}';
    }




}


